[project]
name = "cold-experiments-obs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adjusttext>=1.3.0",
    "cmocean>=4.0.3",
    "ipdb>=0.13.13",
    "matplotlib>=3.5.1",
    "metpy>=1.6.3",
    "netcdf4>=1.7.2",
    "numba>=0.61.0",
    "pandas>=2.2.3",
    "pyproj>=3.7.1",
    "pyshp>=2.3.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.8.0",
    "shapely>=1.8.5",
    "tqdm>=4.67.1",
    "xgrads>=0.2.6",
]
